"""CSV and PDF export."""
import io
from datetime import datetime

import pandas as pd
from PIL import Image
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Image as RLImage
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from pcbdet.visualization import create_metrics

CSV_COLUMNS = ["Image Filename", "Defect Type", "Confidence", "X1", "Y1", "X2", "Y2", "Area (px²)", "Timestamp"]


def _rows(detections, filename, ts):
    return [[filename, d["class"], round(d["confidence"], 4), *d["bbox"], d["area"], ts] for d in detections]


def export_csv(detections: list, image_filename: str) -> bytes:
    return export_batch_csv({image_filename: detections})


def export_batch_csv(results_by_file: dict) -> bytes:
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    rows = [r for name, dets in results_by_file.items() for r in _rows(dets, name, ts)]
    # utf-8-sig so Excel reads the "²" correctly
    return pd.DataFrame(rows, columns=CSV_COLUMNS).to_csv(index=False).encode("utf-8-sig")


def get_pdf_filename() -> str:
    return f"PCB_Detection_{datetime.now():%Y-%m-%d_%H%M%S}.pdf"


def _rl_image(img: Image.Image, max_w_mm: float, max_h_mm: float):
    buf = io.BytesIO()
    img.convert("RGB").save(buf, "JPEG", quality=85)
    buf.seek(0)
    w, h = img.size
    scale = min(max_w_mm * mm / w, max_h_mm * mm / h)
    return RLImage(buf, width=w * scale, height=h * scale)


def _table(detections):
    data = [["#", "Type", "Conf. (%)", "Bounding box", "Area (px²)"]]
    for i, d in enumerate(sorted(detections, key=lambda d: -d["confidence"])[:25], 1):
        data.append([i, d["class"], f"{d['confidence'] * 100:.1f}", str(d["bbox"]), d["area"]])
    t = Table(data, repeatRows=1)
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1b8a5a")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.grey),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
    ]))
    return t


def _footer(canvas, doc):
    canvas.setFont("Helvetica", 8)
    canvas.drawCentredString(A4[0] / 2, 10 * mm, "Generated by PCB Defect Detection v1.0")


def _build(story) -> bytes:
    buf = io.BytesIO()
    SimpleDocTemplate(buf, pagesize=A4, leftMargin=15 * mm, rightMargin=15 * mm,
                      topMargin=15 * mm, bottomMargin=18 * mm).build(story, onFirstPage=_footer, onLaterPages=_footer)
    return buf.getvalue()


def _summary(detections, conf, model_label):
    m = create_metrics(detections)
    by_type = ", ".join(f"{k}: {v}" for k, v in m["counts"].items()) or "none"
    return (f"Total defects: <b>{m['total']}</b> &nbsp; Avg confidence: <b>{m['avg_conf'] * 100:.1f}%</b><br/>"
            f"By type: {by_type}<br/>Model: {model_label}, input 1024×1024, confidence threshold {conf * 100:.0f}%")


def export_pdf(image, annotated_image, detections, image_filename="result",
               conf=0.25, model_label="YOLO26-seg") -> bytes:
    s = getSampleStyleSheet()
    story = [
        Paragraph("PCB Defect Detection Report", s["Title"]),
        Paragraph(f"{datetime.now():%Y-%m-%d %H:%M:%S} — {image_filename}", s["Normal"]),
        Spacer(1, 4 * mm),
        Table([[_rl_image(image, 85, 85), _rl_image(annotated_image, 85, 85)]]),
        Spacer(1, 4 * mm),
        Paragraph(_summary(detections, conf, model_label), s["Normal"]),
        Spacer(1, 4 * mm),
    ]
    story.append(_table(detections) if detections else Paragraph("No defects detected.", s["Normal"]))
    return _build(story)


def export_comparison_pdf(a: dict, b: dict, conf=0.25, model_label="YOLO26-seg") -> bytes:
    """a and b: {'name','annotated','detections'}."""
    s = getSampleStyleSheet()
    na, nb = len(a["detections"]), len(b["detections"])
    delta = na - nb
    verdict = f"{delta} fewer defects" if delta > 0 else f"{-delta} more defects" if delta < 0 else "no change"
    story = [
        Paragraph("PCB Comparison Report", s["Title"]),
        Paragraph(f"{datetime.now():%Y-%m-%d %H:%M:%S}", s["Normal"]),
        Spacer(1, 4 * mm),
        Table([[_rl_image(a["annotated"], 85, 85), _rl_image(b["annotated"], 85, 85)],
               [a["name"], b["name"]]]),
        Spacer(1, 4 * mm),
        Paragraph(f"First: <b>{na}</b> defects &nbsp; Second: <b>{nb}</b> defects &nbsp; Change: <b>{verdict}</b>",
                  s["Normal"]),
        Paragraph(f"Model: {model_label}, input 1024×1024, confidence threshold {conf * 100:.0f}%", s["Normal"]),
        Spacer(1, 4 * mm),
        Paragraph(f"Details — {a['name']}", s["Heading3"]),
        _table(a["detections"]) if a["detections"] else Paragraph("No defects.", s["Normal"]),
        Paragraph(f"Details — {b['name']}", s["Heading3"]),
        _table(b["detections"]) if b["detections"] else Paragraph("No defects.", s["Normal"]),
    ]
    return _build(story)
